### PR TITLE
added can_ to prevent permission issue.

### PR DESCRIPTION
**Pull request by mirfan899**
Django 2.2.1 permission issue fixed.

### CODE REVIEW

**Comment by areski** [comment]
Can you give further information about the issue you are having ?

**Comment by mirfan899** [comment]
https://github.com/areski/django-audiofield/issues/34

**Comment by areski** [comment]
Thanks!

**Comment by Smangaliso007** [comment]
Hey @mirfan899,

Your solutions seems to have produced another ERROR for me. When I checked briefly the CHECKS returned to me in DEBUG it was registered as E.008-- Permission name is longer than (X) CHARS


I am pretty new at coding so this might also be inexeperience. I am using Intellij Idea if that would matter

**Comment by mirfan899** [comment]
@Smangaliso007 Django version?

**Comment by Smangaliso007** [comment]
I am using Django 2.2.4

**Comment by Smangaliso007** [comment]
I am using Django==2.2.4

**Comment by Smangaliso007** [comment]
I think I solved that particular problem.

It was aboout the audio-field version I had installed, it didn't seem to understand how to implement [can_view_audiofile] because I deleted it and reinstalled this one here with that option for Permission.

However now, the Permission's clash problem is still persisting.
I am wondering what would happen if I reverted Django Version to 2.2.1

**Comment by mirfan899** [comment]
You need to install from develop branch. Fix is not release yet. The latest release is of May.

**Comment by Smangaliso007** [comment]
So I just installed the Distribution from development and I still got the following error:

ERRORS:
audiofield.AudioFile: (auth.E005) The permission codenamed 'view_audiofile' clashes with a builtin permission for model 'audiofield.AudioFile'.

I do not understand why it doesn't reject the permission as "can_view_" but does so as "view_"??

**Comment by mirfan899** [comment]
You are missing something. I've used it for more than two Django apps. Here are my packages
```text
amqp==2.5.1
billiard==3.6.1.0
celery==4.4.0rc3
certifi==2019.6.16
chardet==3.0.4
dj-database-url==0.5.0
Django==2.2.4
django-audiofield==0.10.0
django-celery==3.3.1
django-heroku==0.3.1
gunicorn==19.9.0
idna==2.8
importlib-metadata==0.20
kombu==4.6.4
more-itertools==7.2.0
psycopg2==2.8.3
pytz==2019.2
requests==2.22.0
six==1.12.0
sqlparse==0.3.0
urllib3==1.25.3
vine==1.3.0
whitenoise==4.1.3
zipp==0.6.0
```
Screen Shot 2019-09-06 at 9 15 18 PM
Screen Shot 2019-09-06 at 9 15 09 PM
and here are screenshots of my app.

**Comment by Smangaliso007** [comment]
Okay I see where the problem might be, perhaps my configuration might be the problem.

I have included a screenshot that perhaps might help identify how this error is arrived at, I had a look at checks.py but I cant see what I have to change to solve.

It also seems that if I include code to create my own model then I get two MODELS in my admin, _audio files & my_model_ which I see how that could bring a problem. 
So I remove the code to create _my_model_ and the _audio files _ still appears with the same code error???
127 0 0 1_8000_admin_
127 0 0 1_8000_admin_audiofield_audiofile_add_

**Comment by Smangaliso007** [comment]
Sorry I forgot to cut the screenshot but I also realized that this might give more insight into the Debugging, given the enire program environment variables are here

**Comment by Smangaliso007** [comment]
What type field should the model I add the Audiofield to be??

**Pull request merged**
